[package]
name = "louvain-cli"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
# Workspace dependencies
louvain-application = "0.0.0"

# External dependencies
clap = { version = "4.0", features = ["derive"] }
