[book]
authors = ["Splines"]
language = "en"
multilingual = false
src = "src"
title = "Fast Louvain"

[output.html]
default-theme = "light"
curly-quotes = true
mathjax-support = true
git-repository-url = "https://github.com/splines/fast-louvain"

[preprocessor.katex]
after = ["links"]
