# See https://doc.rust-lang.org/cargo/guide/continuous-integration.html#github-actions

on: [push, pull_request]

name: Rust CI

env: 
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        run: rustup update stable && rustup default stable
      
      - name: Run cargo check
        run: cargo check --lib --workspace

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        run: rustup update stable && rustup default stable

      - name: Run cargo test
        run: RUSTFLAGS=-Awarnings cargo test --lib --workspace --no-fail-fast

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        # for components, see https://rust-lang.github.io/rustup/concepts/components.html#components
        run: rustup update stable && rustup default stable && rustup component add rustfmt clippy

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all -- -D warnings
